;--Generated By Que!--
%include "stdmac.asm"
bits 64
default rel
section .text
global SYSCALL
SYSCALL:
	push rbp
	mov rbp, rsp
	sub rsp, 112
	.l_saveregs
	mov qword [rbp-56], rdi
	mov qword [rbp-64], rsi
	mov qword [rbp-72], rdx
	mov qword [rbp-80], rcx
	mov qword [rbp-88], r8
	mov qword [rbp-96], r9

    mov rax, [rbp-56]
    mov rdi, [rbp-64]
    mov rsi, [rbp-72]
    mov rdx, [rbp-80]
    mov r10, [rbp-88]
    mov r8, [rbp-96]
    mov r9, [rbp+16]
    syscall 

	.l_dropregs
	mov rsp, rbp
	pop rbp
	ret
